create or replace
PACKAGE PK_CADASTRO_EMP AS

FUNCTION FC_EXISTE(wp_rc_emp PK_ESTRUTURA_DADOS.tp_rec_emp)
RETURN BOOLEAN;

PROCEDURE PR_INCLUIR(wp_rc_emp in out PK_ESTRUTURA_DADOS.tp_rec_emp);


END PK_CADASTRO_EMP;